name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build e Deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: us-central1
      SERVICE_NAME: bullla-gcs-trigger
      IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bullla-incoming-repo/bullla-gcs-trigger

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Autenticar Docker no Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build da imagem Docker
        run: |
          docker build \
            -t $IMAGE_NAME:${{ github.sha }} \
            -t $IMAGE_NAME:latest .

      - name: Push da imagem para o Artifact Registry
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image=$IMAGE_NAME:${{ github.sha }} \
            --region=$REGION \
            --service-account=bullla-incoming-sa@$PROJECT_ID.iam.gserviceaccount.com \
            --no-allow-unauthenticated \
            --quiet